---
name: CI
# yamllint disable-line rule:truthy
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Get python version
        run: sed -n "s/^FROM \(.*\/\)\?python:\([0-9\.]\+\).*/\2/p" Dockerfile > .python-version
      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  #v7.0.0
        with:
          python-version-file: ".python-version"
      - name: Install python dependencies
        run: pip3 install -c requirements-dev.txt ruff
      - name: Run ruff check
        run: ruff check kruoka.py
      - name: Run ruff format
        run: ruff format --check kruoka.py
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - ruff
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Build Docker image
        run: docker build -t kruoka:latest .
      - name: Start container
        run: docker run --rm -d --name kruoka -p 8000:8000 kruoka:latest
      - name: Test endpoint
        run: python3 test_api.py
      - name: Stop container
        if: always()
        run: |
          docker stop kruoka
